name: Periodic health check

on:
  schedule:
    - cron:  '0 0 20 * *'

jobs:
  health_check:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Health check
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://full-stack-open-pokedex-damp-snowflake-873.fly.dev/
          max-attempts: 3